/// Flutter icons BrazilIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrazilIcon
///      fonts:
///       - asset: fonts/BrazilIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BrazilIcon {
  BrazilIcon._();

  static const _kFontFam = 'BrazilIcon';

  static const IconData emojione_monotone_flag_for_flag_brazil = IconData(0xe800, fontFamily: _kFontFam);
}
